;;; anvil-server-hook-error-test.el --- Bounded hook diagnostics -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'json)
(require 'anvil-server)

(defun anvil-hook-test--exercise (kind condition &optional name)
  "Invoke KIND hook with CONDITION, capturing its logger inputs and response."
  (let* ((name (or name "probe"))
         (original-error (list 'error "original"))
         (hook-input nil) (logs nil) (response nil)
         (hook (lambda (&rest args)
                 (setq hook-input args)
                 (when condition (signal (car condition) (cdr condition)))))
         (anvil-server-tool-error-hook (and (eq kind 'error) (list hook)))
         (anvil-server-tool-dispatch-hook (and (eq kind 'dispatch) (list hook)))
         (anvil-server--tools (make-hash-table :test #'equal))
         (table (make-hash-table :test #'equal)))
    (cl-letf (((symbol-function 'message)
               (lambda (control &rest args)
                 (let ((text (apply #'format control args)))
                   (when (string-prefix-p "anvil-server:" text)
                     (push text logs))
                   text))))
      (if (eq kind 'error)
          (anvil-server--run-tool-error-hook original-error name 'tool-body)
        (puthash name (list :handler (lambda () "hello-é") :arglist nil) table)
        (puthash "emacs-eval" table anvil-server--tools)
        (setq response
              (let ((wire (anvil-server--handle-tools-call
                           "hook-9" `((name . ,name))
                           (make-anvil-server-metrics) "emacs-eval")))
                (let ((json-false nil)) (json-read-from-string wire))))))
    (list :logs (nreverse logs) :hook-input hook-input
          :original original-error :response response)))

(ert-deftest anvil-hook-error-payload-bounded-before-native-formatting ()
  (dolist (kind '(error dispatch))
    (let* ((condition (list 'error (make-string 200000 ?界)))
           (original (symbol-function 'error-message-string))
           (observed nil))
      (cl-letf (((symbol-function 'error-message-string)
                 (lambda (value)
                   (setq observed value)
                   (funcall original value))))
        (anvil-hook-test--exercise kind condition))
      (should observed)
      (should-not (eq observed condition))
      (should (<= (length (cadr observed)) 4096)))))

(ert-deftest anvil-hook-error-metadata-bounded-before-native-formatting ()
  (dolist (kind '(error dispatch))
    (let* ((symbol (make-symbol "hook-large"))
           (metadata (make-string 200000 ?界))
           (original (symbol-function 'error-message-string))
           (observed nil) (result nil))
      (put symbol 'error-message metadata)
      (put symbol 'error-conditions '(error))
      (cl-letf (((symbol-function 'error-message-string)
                 (lambda (value)
                   (setq observed (car value))
                   (funcall original value))))
        (setq result (anvil-hook-test--exercise kind (list symbol "detail"))))
      (should observed)
      (should-not (eq observed symbol))
      (should (<= (length (get observed 'error-message)) 4096))
      (should (eq (get symbol 'error-message) metadata))
      (should (< (length (car (plist-get result :logs))) 4500)))))

(ert-deftest anvil-hook-error-small-diagnostics-remain-compatible ()
  (should (equal (plist-get (anvil-hook-test--exercise 'error '(error "small")) :logs)
                 '("anvil-server: tool-error-hook failed: small")))
  (should (equal (plist-get (anvil-hook-test--exercise 'dispatch '(error "small")) :logs)
                 '("anvil-server: dispatch-hook error on probe: small"))))

(ert-deftest anvil-hook-error-preserves-original-hook-arguments ()
  (let ((result (anvil-hook-test--exercise 'error '(error "hook failure"))))
    (should (eq (car (plist-get result :hook-input)) (plist-get result :original)))
    (should (equal (cdr (plist-get result :hook-input)) '("probe" tool-body))))
  (let* ((result (anvil-hook-test--exercise 'dispatch '(error "hook failure")))
         (response (plist-get result :response))
         (content (alist-get 'content (alist-get 'result response))))
    (should (equal (plist-get result :hook-input) '("probe" "emacs-eval")))
    (should (equal (alist-get 'id response) "hook-9"))
    (should-not (alist-get 'error response))
    (should-not (alist-get 'isError (alist-get 'result response)))
    (should (equal (alist-get 'text (aref content 0)) "hello-é"))
    (should (equal response
                   (plist-get (anvil-hook-test--exercise 'dispatch nil) :response)))))

(ert-deftest anvil-hook-error-dispatch-tool-name-is-bounded ()
  (let* ((name (make-string 200000 ?界))
         (result (anvil-hook-test--exercise 'dispatch '(error "small") name))
         (log (car (plist-get result :logs))))
    (should log)
    (should (< (length log) 300))
    (should (eq (car (plist-get result :hook-input)) name))
    (should (string-suffix-p ": small" log))))

(ert-deftest anvil-hook-error-server-work-budgets-remain-pinned ()
  (dolist (kind '(error dispatch))
    (let ((anvil-bounded-data--snapshot-node-limit 200000)
          (anvil-bounded-data--snapshot-depth-limit 200000)
          (anvil-bounded-data--snapshot-char-limit 200000)
          (original (symbol-function 'error-message-string))
          (observed nil))
      (cl-letf (((symbol-function 'error-message-string)
                 (lambda (value)
                   (setq observed
                         (list anvil-bounded-data--snapshot-node-limit
                               anvil-bounded-data--snapshot-depth-limit
                               anvil-bounded-data--snapshot-char-limit))
                   (funcall original value))))
        (anvil-hook-test--exercise kind (list 'error (make-string 200000 ?x))))
      (should (equal observed '(512 8 4096))))))

(ert-deftest anvil-hook-error-cyclic-metadata-never-reaches-native-formatter ()
  (dolist (kind '(error dispatch))
    (let* ((symbol (make-symbol "hook-cycle"))
           (properties (list 'error-conditions '(error) 'error-message "safe"))
           (original (symbol-function 'error-message-string))
           (observed nil))
      (setcdr (last properties) properties)
      (setplist symbol properties)
      ;; Avoid traversing the original cyclic plist in the baseline formatter.
      (cl-letf (((symbol-function 'error-message-string)
                 (lambda (value)
                   (setq observed (car value))
                   (if (eq (car value) symbol) "unsafe original metadata"
                     (funcall original value)))))
        (anvil-hook-test--exercise kind (list symbol)))
      (should-not (eq observed symbol))
      (should (equal (get observed 'error-message) "safe")))))

(provide 'anvil-server-hook-error-test)
;;; anvil-server-hook-error-test.el ends here
