;;; anvil-harness-telemetry-bounds-test.el --- Bounds for error telemetry -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'anvil-harness-telemetry)

(ert-deftest anvil-ht-bounds-snapshot-forwards-dynamic-private-limits ()
  (let ((anvil-harness-telemetry--snapshot-node-limit 3)
        (anvil-harness-telemetry--snapshot-depth-limit 2)
        (anvil-harness-telemetry--snapshot-char-limit 17)
        (captured nil)
        (sentinel (list :sentinel t)))
    (cl-letf (((symbol-function 'anvil-bounded-data--bounded-snapshot)
               (lambda (value &optional maxchars)
                 (setq captured
                       (list value maxchars
                             anvil-bounded-data--snapshot-node-limit
                             anvil-bounded-data--snapshot-depth-limit
                             anvil-bounded-data--snapshot-char-limit))
                 sentinel)))
      (should (eq (anvil-harness-telemetry--bounded-snapshot 'input 11)
                  sentinel)))
    (should (equal captured '(input 11 3 2 17)))))

(ert-deftest anvil-ht-bounds-raw-context-does-not-render-original-error ()
  "Raw context must be assembled within a bounded renderer."
  (let ((hostile (list 'error (make-string 1000000 ?x)))
        (original-format (symbol-function 'format))
        (seen-hostile nil))
    (cl-letf (((symbol-function 'format)
              (lambda (control &rest args)
                (when (and (stringp control)
                           (string-match-p "%S" control)
                           (memq hostile args))
                  (setq seen-hostile t))
                (apply original-format control args))))
      (let ((raw (anvil-harness-telemetry--raw-context hostile)))
        (should (<= (length raw) 500))
        (should-not seen-hostile)))))

(ert-deftest anvil-ht-bounds-error-message-is-capped-before-classification ()
  "An error-message property must not make rendered telemetry unbounded."
  (let* ((error-name (intern (concat "anvil-ht-large-error-" (make-string 200000 ?n))))
         (anvil-harness-telemetry-error-message-max-chars 4096)
         (message-text (make-string 1000000 ?x)))
    (put error-name 'error-message message-text)
    (unwind-protect
        (let ((message (anvil-harness-telemetry--error-message
                        (list error-name 'payload))))
          (should (<= (length message) 4096)))
      (put error-name 'error-message nil))))

(ert-deftest anvil-ht-bounds-snapshot-prefix-and-properties ()
  (let* ((s (propertize (make-string 100000 ?界) 'secret t))
         (snap (anvil-harness-telemetry--bounded-snapshot s 17))
         (out (plist-get snap :value)))
    (should (= (length out) 17))
    (should-not (text-properties-at 0 out))
    (should (= (plist-get snap :chars) 17))))

(ert-deftest anvil-ht-bounds-snapshot-vector-reads-are-bounded ()
  (let* ((v (make-vector 100000 nil)) (reads 0)
         (aref0 (symbol-function 'aref)))
    (cl-letf (((symbol-function 'aref)
               (lambda (x i) (when (eq x v) (setq reads (1+ reads))) (funcall aref0 x i))))
      (let ((snap (anvil-harness-telemetry--bounded-snapshot v)))
        (should (<= reads 512))
        (should (<= (plist-get snap :nodes) 512))
        (should (<= (plist-get snap :chars) 4096))))))

(ert-deftest anvil-ht-bounds-snapshot-cycles-and-opaque-values ()
  (let* ((cycle (list 'x)) (big (expt 2 10000)))
    (setcdr cycle cycle)
    (let* ((snap (anvil-harness-telemetry--bounded-snapshot
                  (vector cycle big (make-hash-table) (make-string 129 ?s))))
           (v (plist-get snap :value)))
      (should (equal (aref v 1) "<opaque>"))
      (should (equal (aref v 2) "<opaque>"))
      (should (<= (plist-get snap :nodes) 512))
      (should (<= (plist-get snap :chars) 4096)))))

(ert-deftest anvil-ht-bounds-snapshot-deep-and-branching-graphs-stop ()
  (let* ((deep (make-list 32 'leaf)) (branch (make-vector 10000 deep))
         (snap (anvil-harness-telemetry--bounded-snapshot branch)))
    (should (<= (plist-get snap :nodes) 512))
    (should (<= (plist-get snap :chars) 4096))
    (should (string-match-p "depth" (format "%S" (plist-get snap :value)))))
  (let* ((object (record 'anvil-ht-record 1 2))
         (snap (anvil-harness-telemetry--bounded-snapshot object)))
    (should (equal (plist-get snap :value) "<opaque>"))))

(ert-deftest anvil-ht-bounds-message-small-conditions-match-native-renderer ()
  (dolist (err (list (list 'void-function 'absent)
                     (list 'wrong-type-argument 'listp 3)
                     (list 'file-error "oops" "/tmp/a")
                     (list 'anvil-ht-custom-condition "detail")
                     (list 'error "small")))
    (should (equal (anvil-harness-telemetry--error-message err)
                   (error-message-string err))))
  (should (equal (anvil-harness-telemetry--error-message "exact") "exact")))

(ert-deftest anvil-ht-bounds-message-metadata-is-cloned-and-capped ()
  (let* ((name (make-symbol "anvil-ht-private-error"))
         (payload (make-string 1000000 ?x))
         (original (symbol-function 'error-message-string))
         (captured-head nil) (captured-meta-length nil))
    (put name 'error-conditions '(anvil-ht-private-error error))
    (put name 'error-message payload)
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'error-message-string)
                     (lambda (err)
                       (setq captured-head (car err)
                             captured-meta-length (length (get (car err) 'error-message)))
                       (funcall original err))))
            (should (<= (length (anvil-harness-telemetry--error-message (list name 'x))) 4096)))
          (should-not (eq captured-head name))
          (should (<= (length (symbol-name captured-head)) 128))
          (should (<= captured-meta-length 4096)))
      ;; Guard negative control: the same assertions reject the unsafe input.
      (let ((bad-head name) (bad-meta-length (length payload)))
        (should-error
         (should-not (eq bad-head name))
         :type 'ert-test-failed)
        (should-error
         (should (<= bad-meta-length 4096))
         :type 'ert-test-failed))
      (setplist name nil))))

(ert-deftest anvil-ht-bounds-message-key-sequence-metadata-is-elided ()
  (let ((name (make-symbol "anvil-ht-key-error")))
    (put name 'error-conditions '(anvil-ht-key-error error))
    (put name 'error-message "Press \\[anvil-command]")
    (unwind-protect
        (should (string-match-p "elided" (anvil-harness-telemetry--error-message (list name))))
      (setplist name nil))))

(ert-deftest anvil-ht-bounds-caps-normalize-zero-invalid-and-excessive ()
  (dolist (limit '(0 1 -1 nope 9000))
    (let ((anvil-harness-telemetry-error-message-max-chars limit)
          (anvil-harness-telemetry-raw-context-max-chars limit))
      (let ((rendered (anvil-harness-telemetry--render-error
                       (list 'error (make-string 10000 ?x)))))
        (should (<= (length (plist-get rendered :message))
                    (if (and (integerp limit) (>= limit 0)) (min limit 4096) 4096)))
        (should (<= (length (plist-get rendered :raw-context))
                    (if (and (integerp limit) (>= limit 0)) (min limit 4096) 500)))))))

(ert-deftest anvil-ht-bounds-classifier-preserves-rule-order-and-source-shortcut ()
  (let ((anvil-harness-telemetry-classifier-rules
         '((first :regex ("needle")) (later :error-symbols (some-error)))))
    (should (equal (anvil-harness-telemetry--classify '(some-error "needle")) '(first . 1.0))))
  (cl-letf (((symbol-function 'anvil-harness-telemetry--render-error)
             (lambda (_err) (error "renderer must not run"))))
    (should (equal (anvil-harness-telemetry--classify '(wrong-type-argument x) :source 'tool-body)
                   '(no-exec . 1.0)))))

(ert-deftest anvil-ht-bounds-record-renders-once-and-bounds-tool ()
  (let ((calls 0) (tool (make-string 100000 ?t)))
    (cl-letf (((symbol-function 'anvil-harness-telemetry--render-error)
               (lambda (_err) (setq calls (1+ calls))
                 (list :message "small" :raw-context "raw")))
              ((symbol-function 'anvil-harness-telemetry-record)
               (lambda (&rest args) args)))
      (let ((result (anvil-harness-telemetry-record-from-error '(error "x") :tool tool)))
        (should (= calls 1))
        (should (<= (length (plist-get (cdr result) :tool)) 128))))))

(ert-deftest anvil-ht-bounds-failure-log-does-not-render-error-data ()
  (let ((messages nil) (hostile (make-string 100000 ?x)))
    (cl-letf (((symbol-function 'anvil-harness-telemetry-record)
               (lambda (&rest _args) (signal 'error (list hostile))))
              ((symbol-function 'message)
               (lambda (&rest args) (push args messages))))
      (should-not (anvil-harness-telemetry-record-from-error '(error "small")))
      (should (equal messages '(("anvil-harness-telemetry: record-from-error swallowed")))))))

(ert-deftest anvil-ht-bounds-error-conditions-cycle-stops-bounded ()
  (let* ((name (make-symbol "anvil-ht-cyclic-error"))
         (conditions (list 'anvil-ht-cyclic-error)))
    (setcdr conditions conditions)
    (put name 'error-conditions conditions)
    (put name 'error-message "safe")
    (unwind-protect
        (should (<= (length (anvil-harness-telemetry--error-message (list name))) 16))
      (setplist name nil))))

(ert-deftest anvil-ht-bounds-symbol-plist-traversal-has-cdr-budget ()
  (let* ((name (make-symbol "anvil-ht-long-plist"))
         (reads 0) (original-cdr (symbol-function 'cdr))
         (watched (make-hash-table :test #'eq)))
    (let ((padding nil))
      (dotimes (i 400)
        (setq padding (append padding (list (intern (format "anvil-ht-padding-%d" i)) i))))
      (setplist name (append padding '(error-message "late safe message"
                                     error-conditions (file-error error)))))
    (let ((tail (symbol-plist name)))
      (while (consp tail)
        (puthash tail t watched)
        (let ((value-cell (funcall original-cdr tail)))
          (unless (consp value-cell) (setq tail nil))
          (when (consp value-cell)
            (puthash value-cell t watched)
            (setq tail (funcall original-cdr value-cell))))))
    (cl-letf (((symbol-function 'cdr)
               (lambda (cell)
                 (when (gethash cell watched) (setq reads (1+ reads)))
                 (funcall original-cdr cell))))
      (let ((props (anvil-harness-telemetry--bounded-symbol-properties name)))
        (should (<= reads 512))
        (should (<= (plist-get props :steps) 512))
        (should (plist-get props :truncated))
        (should-not (plist-get props :error-message))))
    (setplist name nil)))

(ert-deftest anvil-ht-bounds-symbol-plist-cycle-and-malformation-terminate ()
  (let* ((cycle-name (make-symbol "anvil-ht-plist-cycle"))
         (plist (list 'error-message "safe")))
    (setcdr (cdr plist) plist)
    (setplist cycle-name plist)
    (should (plist-get (anvil-harness-telemetry--bounded-symbol-properties cycle-name) :truncated))
    (should (equal (anvil-harness-telemetry--error-message (list cycle-name)) "safe"))
    (setplist cycle-name (list 'error-message))
    (should (plist-get (anvil-harness-telemetry--bounded-symbol-properties cycle-name) :truncated))
    (should (<= (length (anvil-harness-telemetry--error-message (list cycle-name))) 4096))
    (setplist cycle-name nil)))

(ert-deftest anvil-ht-bounds-symbol-plist-keeps-first-duplicate-value ()
  (let ((name (make-symbol "anvil-ht-duplicate-plist")))
    (setplist name '(error-message nil error-message "later" error-conditions (error)))
    (should-not (plist-get (anvil-harness-telemetry--bounded-symbol-properties name)
                           :error-message))
    (setplist name nil)))

(ert-deftest anvil-ht-bounds-shared-renderer-forwards-all-private-limits ()
  (let ((anvil-harness-telemetry--snapshot-node-limit 6)
        (anvil-harness-telemetry--snapshot-depth-limit 2)
        (anvil-harness-telemetry--snapshot-char-limit 17)
        (anvil-harness-telemetry-error-message-max-chars 9)
        (anvil-harness-telemetry-raw-context-max-chars 4)
        (observed nil))
    (cl-letf (((symbol-function 'anvil-bounded-data--render-snapshot)
               (lambda (_snapshot &optional message-max raw-max)
                 (setq observed
                       (list anvil-bounded-data--snapshot-node-limit
                             anvil-bounded-data--snapshot-depth-limit
                             anvil-bounded-data--snapshot-char-limit
                             message-max raw-max))
                 '(:message "safe" :raw-context "raw"))))
      (should (equal (anvil-harness-telemetry--render-snapshot '(:value "x"))
                     '(:message "safe" :raw-context "raw"))))
    (should (equal observed '(6 2 17 9 4)))))

(ert-deftest anvil-ht-bounds-private-metadata-helpers-preserve-dynamic-limits ()
  (let ((anvil-harness-telemetry--snapshot-node-limit 2)
        (anvil-harness-telemetry--snapshot-char-limit 5)
        (symbol (make-symbol "helper-limits")))
    (setplist symbol '(padding t error-message "late" error-conditions (file-error error)))
    (should (= (anvil-harness-telemetry--finite-limit 99 4096) 5))
    (should (= (anvil-harness-telemetry--finite-limit nil 4096) 4096))
    (should (= (plist-get (anvil-harness-telemetry--bounded-symbol-properties symbol) :steps) 2))
    (should-not (plist-get (anvil-harness-telemetry--bounded-symbol-properties symbol) :error-message))
    (should (equal (anvil-harness-telemetry--safe-condition-names
                    symbol '(custom error file-error)) '(error)))))

(provide 'anvil-harness-telemetry-bounds-test)
;;; anvil-harness-telemetry-bounds-test.el ends here
